# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.TextField(default='Bob Marley', max_length=1000),
            preserve_default=False,
        ),
    ]
